require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { startScheduler } = require('./scheduler');
const { helmetMiddleware, authLimiter, apiLimiter } = require('./middleware/security');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(helmetMiddleware);
app.use(cors({ origin: process.env.FRONTEND_URL || '*', methods: ['GET','POST','PATCH','DELETE'], allowedHeaders: ['Content-Type','Authorization'], credentials: true }));
app.use(express.json({ limit: '100kb' }));
app.use('/api/auth', authLimiter);
app.use('/api', apiLimiter);
app.use('/api/billing/webhook', express.raw({ type: 'application/json' }));
app.use('/api/auth', require('./src/routes/auth'));
app.use('/api/automations', require('./src/routes/automations'));
app.use('/api/logs', require('./src/routes/logs'));
app.use('/api/billing', require('./src/routes/billing'));
app.get('/health', (req, res) => res.json({ status: 'ok' }));
app.use((req, res) => res.status(404).json({ error: 'Not found' }));
app.use((err, req, res, next) => res.status(500).json({ error: 'Internal server error' }));
app.listen(PORT, () => { console.log('🚀 Flowra API running on port ' + PORT); startScheduler(); });
